### ISSUE TITLE
Select a date and calendarListener.onDateSelected() callback two times

### ISSUE THREAD

**Issue by lmdiloveu** [Mulham-Raee/Horizontal-Calendar#34] opened 2017-08-02 12:04 UTC
Select a date and calendarListener.onDateSelected() callback two times . Every time a date is selected, I need to access the network interface once , causes my code to access the two network interface，how to fix it?

**Comment by tonyannick** [comment] 2017-08-05 00:19
same for me....... the date is selected itself in oncreate method and make a network request.

**Comment by Mulham-Raee** [comment] 2017-10-19 19:29
possible duplicate of #28

**Closed** 2017-10-25 15:10 UTC
Labels: invalid
