### ISSUE TITLE
Calendar defaults to yesterday/tomorrow when datesNumberOnScreen set to 3 

### ISSUE THREAD

**Issue by mg931** [Mulham-Raee/Horizontal-Calendar#58] opened 2017-12-01 16:15 UTC
Thank you for the work that's gone into this very useful library. 

Unfortunately I am experiencing an issue where the calendar always defaults to tomorrow's date (occasionally yesterday's). I'am configuring the Calendar as shown below... 

`private HorizontalCalendar initCalendar() {
        Calendar endDate = Calendar.getInstance();
        endDate.add(Calendar.DAY_OF_MONTH, 1);
        Calendar startDate = Calendar.getInstance();
        startDate.add(Calendar.DAY_OF_MONTH, -1);

        return new HorizontalCalendar.Builder(this, R.id.calendarView)
                .startDate(startDate.getTime())
                .endDate(endDate.getTime())
                .datesNumberOnScreen(3)   // Number of Dates cells shown on screen (Recommended 5)
                .dayNameFormat("EEE")      // WeekDay text format
                .dayNumberFormat("dd")    // Date format
                .monthFormat("MMM")      // Month format
                .showDayName(true)          // Show or Hide dayName text
                .showMonthName(true)      // Show or Hide month text
                .textColor(Color.LTGRAY, Color.WHITE)    // Text color for none selected Dates
                .selectorColor(Color.BLUE)   // Color of the selection indicator bar (default to colorAccent).
                .build();

    }`

The value of 'onDateSelected' when the calendar is initialised is always today's date yet the Calendar shows tomorrow as selected. I understand that the recommended 'datesNumberOnScreen' value is 5 and i've found that this issue doesn't happen when changing the value of 5.

I would ideally like to show 3 dates if this is possible, and I've tried setting defaultSelectedDate() to today and running goToday(true) without success. 

I've tested a previous version of my project - with datesNumberOnScreen set to 3 - and it works as expected. This has started happening in a branch where I have made a number of upgrades to my project including upgrading to 'com.android.tools.build:gradle:3.0.1'

Any assistance with this issue would be much appreciated. Many thanks

**Comment by Luopan1** [comment] 2017-12-05 14:06
use his source code as library to your peoject,and if you want to set datesNumberOnScreen() as 3 ,you would change one function in his soucrce code :
private void centerToPositionWithNoAnimation(final int position) {
`if(position != -1) {
int shiftCells = numberOfDatesOnScreen / 2;
int centerItem = calendarView.getPositionOfCenterItem();

        if (position > centerItem) {

            // TODO: 2017/11/27  changed when set datesNumberOnScreen(3)
            calendarView.scrollToPosition(position + shiftCells - 1);

        } else if (position < centerItem) {
            calendarView.scrollToPosition(position - shiftCells);
        }

        calendarView.post(new Runnable() {
            @Override
            public void run() {
                mCalendarAdapter.notifyDataSetChanged();
            }
        });
    }
}`

the todo  is change code  
if you are puzzled with my description，forgive my poor english.

**Comment by mg931** [comment] 2017-12-06 09:50
thanks for your reply @Luopan1 

I've had to switch to a different library for time being but will test this out.

**Comment by Mulham-Raee** [comment] 2017-12-15 22:07
duplicate of #57, which was fixed.

**Closed by Mulham-Raee** 2017-12-15 22:07 UTC
Labels: duplicate

**Comment by AnjuJohnson** [comment] 2018-07-05 07:46
How to set start date to today date?I have trieed but still showing previous dates

**Comment by Luopan1** [comment] 2018-07-05 08:01
consult the  sample code,but the datesNumberOnScreen set to 3, [(https://raw.githubusercontent.com/Luopan1/HeTongBox/ad3fa2402b68b2828a54d7369383792a60b3a867/app/src/main/java/com/test720/hetong/module/dynamic/GuiJiActivty.java)](url)
