### ISSUE TITLE
Adding calendar to fragment in sample

### ISSUE THREAD

**Issue by mhussien86** [Mulham-Raee/Horizontal-Calendar#9] opened 2017-03-25 14:16 UTC
There is a crash while trying to add the calender to a fragment instead of activity we can demonstrate a sample for this

**Comment by Mulham-Raee** [comment] 2017-03-25 21:59
Hello @mhussien86 

Please provide me with the crash message from the Android monitor, and a snippet of your code where you init the calendar.

Regards!

**Comment by harshmalhotra** [comment] 2017-03-30 10:26
java.lang.NullPointerException: Attempt to invoke virtual method 'void devs.mulham.horizontalcalendar.HorizontalCalendarView.setHasFixedSize(boolean)' on a null object reference


horizontalCalendar = new HorizontalCalendar.Builder(getActivity(), R.id.calendarView)
                .startDate(startDate.getTime())
                .endDate(endDate.getTime())
                .datesNumberOnScreen(7)
                .dayFormat("EEE")
                .dayNumberFormat("dd")
                .textColor(Color.LTGRAY, Color.WHITE)
                .selectedDateBackground(Color.TRANSPARENT)
                .build();

Please provide the solution..

**Comment by mhussien86** [comment] 2017-03-31 13:47
Hi Guys, yes same error happened as posted from @harshmalhotra , and my solution was to make a field View of my fragment view and get the calendar id and init the calendar in onViewCreated() method, as following : 
`public class MeetingsFragment extends BaseFragment {

    View view ;
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.meetings_fragment, container, false);

        return view;
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        initCalender();
    }

    private void initCalender() {
        Calendar endDate = Calendar.getInstance();
        endDate.add(Calendar.MONTH, 1);

        /** start before 1 month from now */
        Calendar startDate = Calendar.getInstance();
        startDate.add(Calendar.MONTH, -1);

        View calView = view.findViewById(R.id.calendarView);
        HorizontalCalendar horizontalCalendar = new HorizontalCalendar.Builder(getActivity(), calView.getId())
                .startDate(startDate.getTime())
                .endDate(endDate.getTime())
                .build();
        horizontalCalendar.setCalendarListener(new HorizontalCalendarListener() {
            @Override
            public void onDateSelected(Date date, int position) {
                //do something
            }
        });
    }
}`

**Comment by mhussien86** [comment] 2017-03-31 13:48
I can create fragment sample PR if you wish @Mulham-Raee

**Comment by harshmalhotra** [comment] 2017-03-31 13:52
Yes please if you can

**Comment by Mulham-Raee** [comment] 2017-03-31 14:17
Dear @harshmalhotra, @mhussien86 

You don't need to do any special thing to use `HorizonalCalendar `in a fragment, if you check the parameters for the builder you will notice that you can pass a view instead of an Activity, which is the `rootView `of your **fragment**.

Simply init Calendar so:
`HorizontalCalendar horizontalCalendar = new HorizontalCalendar.Builder(rootView, R.id.calendar)`

passing an Activity instead of the rootView of the activity is just meant for simplicity.
Please test it like this and comeback to me, so I can close this issue.

Best Regards
Mulham

**Comment by mhussien86** [comment] 2017-03-31 14:46
@Mulham-Raee  you can colse it .. thanks

**Closed** 2017-03-31 14:46 UTC

**Comment by ChethanAndroid** [comment] 2019-10-23 12:59
Hi @Mulham-Raee 

   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.onelabthyroapp/com.example.onelabthyroapp.TimeSlotActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void devs.mulham.horizontalcalendar.HorizontalCalendar.setCalendarListener(devs.mulham.horizontalcalendar.utils.HorizontalCalendarListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2995)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1774)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7055)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void devs.mulham.horizontalcalendar.HorizontalCalendar.setCalendarListener(devs.mulham.horizontalcalendar.utils.HorizontalCalendarListener)' on a null object reference
        at com.example.onelabthyroapp.TimeSlotActivity.onCreate(TimeSlotActivity.java:127)
        at android.app.Activity.performCreate(Activity.java:7314)
        at android.app.Activity.performCreate(Activity.java:7305)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2948)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1774) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:7055) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836) 
I/Process: Sending signal. PID: 21255 SIG: 9


Please resolve this

**Comment by bevcastillo** [comment] 2020-11-12 06:15
Having this issue with Fragments. Tried to pass the rootview but still getting an error.

**Comment by DEV-SUBHAJIT** [comment] 2021-09-13 13:52
This error will show when you call this class from the fragment. Solution is here

public class ScheduleFragment extends Fragment {

    private HorizontalCalendar horizontalCalendar;

    View view;


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_schedule, container, false);
        initView();
        calender();
        getData();
        clickEvent();
        return view;
    }

    private void initView() {
        
    }

    private void calender() {
        Calendar endDate = Calendar.getInstance();
        endDate.add(Calendar.MONTH, 1);
        Calendar startDate = Calendar.getInstance();
        startDate.add(Calendar.MONTH, -1);


        horizontalCalendar = new HorizontalCalendar.Builder(view, R.id.horizontalCalender)
                .range(startDate, endDate)
                .datesNumberOnScreen(5)
                .build();


        horizontalCalendar.setCalendarListener(new HorizontalCalendarListener() {
            @Override
            public void onDateSelected(Calendar date, int position) {
                Toast.makeText(getActivity(), date + " is selected!", Toast.LENGTH_SHORT).show();
            }
        });
    }

    private void getData() {

    }

    private void clickEvent() {

    }
}
